src/api/urls.py
from django.urls import path
from .apiviews import student_api_views, teacher_api_view

urlpatterns = [
    path('students/', student_api_views.student_list),
    path('teachers/', teacher_api_view.teacher_list),
]

src/dashboard/urls.py
from django.urls import path
from .views import index

app_name = 'dashboard'

urlpatterns = [
    path('dashboard/', index, name='index'),
]

src/monEtabV1_4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('school.urls')),
    path('api/', include('api.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('user/', include('user.urls')),
    path('adress/', include('base.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('report/', include('report.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/report/urls.py
from django.urls import path
from . import views 
 

app_name = 'report'

urlpatterns = [
    path('', views.index, name='index'),
    path('generate-excel-student-list', views.students_list_to_excel, name='students_list_to_excel'),
    path('generate-excel-teacher-list', views.teachers_list_to_excel, name='teachers_list_to_excel'),
    path('generate-excel-user-list', views.users_list_to_excel, name='users_list_to_excel'),
    path('generate-pdf-student-list', views.students_list_to_pdf, name='students_list_to_pdf'),
    path('generate-pdf-teacher-list', views.teachers_list_to_pdf, name='teachers_list_to_pdf'),
    path('generate-pdf-user-list', views.users_list_to_pdf, name='users_list_to_pdf'),

]

src/templates/partials/custom.html
<!-- Custom template | don't include it in your project! -->
<div class="custom-template">
  <div class="title">Paramètre Couleur</div>
  <div class="custom-content">
    <div class="switcher">
      <div class="switch-block">
        <h4>Entête Navigation</h4>
        <div class="btnSwitch">
          <button type="button" class="selected changeTopBarColor" data-color="dark"></button>

          <button type="button" class="changeTopBarColor" data-color="white"></button>

          <button type="button" class="changeTopBarColor" data-color="dark2"></button>

        </div>
      </div>
      <div class="switch-block">
        <h4>Barre de Navigation</h4>
        <div class="btnSwitch">
          <button type="button" class="changeSideBarColor" data-color="white"></button>

          <button type="button" class="selected changeSideBarColor" data-color="dark"></button>

          <button type="button" class="changeSideBarColor" data-color="dark2"></button>

        </div>
      </div>
    </div>
  </div>
  <div class="custom-toggle">
    <i class="icon-settings"></i>
  </div>
</div>
<!-- End Custom template -->

src/templates/partials/footer.html
<footer class="footer">
  <div class="container-fluid">

    <div class="copyright" style="text-align: center; margin-left:40%; margin-right: 40%">
        Copyright &copy; 2024 - <script type="text/javascript">document.write(new Date().getFullYear());</script>
        <noscript>2024</noscript>
        <i class="fa fa-heart heart text-danger"></i>
    </div>

  </div>
</footer>

src/templates/partials/header.html
{% load static %}
      
<div class="main-header">
  <div class="main-header-logo">
    <!-- Logo Header -->
    <div class="logo-header" data-background-color="white">
      <a href="{% url 'dashboard:index' %}" class="logo">
        <img src="{% static 'assets/img/kaiadmin/logo_dark.png' %}" alt="navbar brand" class="navbar-brand" width="200" height="60"/>
      </a>
      <div class="nav-toggle">
        <button class="btn btn-toggle toggle-sidebar">
            <i class="gg-menu-right"></i>
        </button>
        <button class="btn btn-toggle sidenav-toggler">
            <i class="gg-menu-left"></i>
        </button>
      </div>
      <button class="topbar-toggler more">
        <i class="gg-more-vertical-alt"></i>
      </button>
    </div>
    <!-- End Logo Header -->
  </div>
  <!-- Navbar Header -->
  <nav class="navbar navbar-header navbar-header-transparent navbar-expand-lg border-bottom" data-background-color="dark">
    <div class="container-fluid">
      <!-- <nav class="navbar navbar-header-left navbar-expand-lg navbar-form nav-search p-0 d-none d-lg-flex">
        <div class="input-group">
          <div class="input-group-prepend">
            <button type="submit" class="btn btn-search pe-1">
              <i class="fa fa-search search-icon"></i>
            </button>
          </div>
          <input type="text" placeholder="Search ..." class="form-control"/>
        </div>
      </nav> -->

      {% if user.is_authenticated %}

        <ul class="navbar-nav topbar-nav ms-md-auto align-items-center">
          <!-- <li class="nav-item topbar-icon dropdown hidden-caret d-flex d-lg-none">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
              aria-expanded="false" aria-haspopup="true">
              <i class="fa fa-search"></i>
            </a>
            <ul class="dropdown-menu dropdown-search animated fadeIn">
              <form class="navbar-left navbar-form nav-search">
                <div class="input-group">
                  <input type="text" placeholder="Search ..." class="form-control"/>
                </div>
              </form>
            </ul>
          </li> -->

          <li class="nav-item topbar-user dropdown hidden-caret">
            <a
              class="dropdown-toggle profile-pic"
              data-bs-toggle="dropdown"
              href="#"
              aria-expanded="false"
            >
              <div class="avatar-sm">
                <img
                  src="{% static 'assets/img/profile.jpg' %}"
                  alt="..."
                  class="avatar-img rounded-circle"
                />
              </div>
              <span class="profile-username">
                <span class="op-7">Salut,</span>
                <span class="fw-bold"> {{ user.username|upper }} </span>
              </span>
            </a>
            <ul class="dropdown-menu dropdown-user animated fadeIn">
              <div class="dropdown-user-scroll scrollbar-outer">
                <li>
                  <div class="user-box">
                    <div class="avatar-lg">
                      <img
                        src="{% static 'assets/img/profile.jpg' %}"
                        alt="image profile"
                        class="avatar-img rounded"
                      />
                    </div>
                    <div class="u-text">
                      {% if user.teacher %}
                        <h4 class="text-info" >{{ user.teacher.first_name|upper }}</h4>
                        <p class="text-info">{{ user.teacher.last_name|upper }}</p>
                        {% elif user.student %}
                          <h4 class="text-info" >{{ user.student.first_name|upper }}</h4>
                          <p class="text-info">{{ user.student.last_name|upper }}</p>
                        {% else %}
                          <h4 class="text-info" >{{ user.username|upper }}</h4>
                          <p class="text-info">{{ user.email }}</p>
                      {% endif %}
                      
                      <a
                        href="#"
                        class="btn btn-xs btn-secondary btn-sm"
                        >Profil</a
                      >
                    </div>
                  </div>
                </li>
                <li style="font-size: 100px;">
                  <a class="dropdown-item" href="{% url 'user:logout' %}">Déconnexion</a>
                </li>
              </div>
            </ul>
          </li>
        </ul>
        
      {% endif %}
    </div>
  </nav>
  <!-- End Navbar -->
</div>

src/templates/partials/scripts.html
{% load static %}

<!--   Core JS Files   -->
<script src="{% static 'assets/js/core/jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'assets/js/core/popper.min.js' %}"></script>
<script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>

<!-- jQuery Scrollbar -->
<script src="{% static 'assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>

<!-- Chart JS -->
<script src="{% static 'assets/js/plugin/chart.js/chart.min.js' %}"></script>

<!-- jQuery Sparkline -->
<script src="{% static 'assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js' %}"></script>

<!-- Chart Circle -->
<script src="{% static 'assets/js/plugin/chart-circle/circles.min.js' %}"></script>

<!-- Datatables -->
<script src="{% static 'assets/js/plugin/datatables/datatables.min.js' %}"></script>

<!-- Bootstrap Notify -->
<!-- <script src="{% static 'assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js' %}"></script>-->

<!-- jQuery Vector Maps -->
<script src="{% static 'assets/js/plugin/jsvectormap/jsvectormap.min.js' %}"></script>
<script src="{% static 'assets/js/plugin/jsvectormap/world.js' %}"></script>

<!-- Sweet Alert -->
<script src="{% static 'assets/js/plugin/sweetalert/sweetalert.min.js' %}"></script>

<!-- Kaiadmin JS -->
<script src="{% static 'assets/js/kaiadmin.min.js' %}"></script>

<!-- Kaiadmin DEMO methods, don't include it in your project! -->
<script src="{% static 'assets/js/setting-demo.js' %}"></script>
<script src="{% static 'assets/js/demo.js' %}"></script>
<script>
  $("#lineChart").sparkline([102, 109, 120, 99, 110, 105, 115], {
    type: "line",
    height: "70",
    width: "100%",
    lineWidth: "2",
    lineColor: "#177dff",
    fillColor: "rgba(23, 125, 255, 0.14)",
  });

  $("#lineChart2").sparkline([99, 125, 122, 105, 110, 124, 115], {
    type: "line",
    height: "70",
    width: "100%",
    lineWidth: "2",
    lineColor: "#f3545d",
    fillColor: "rgba(243, 84, 93, .14)",
  });

  $("#lineChart3").sparkline([105, 103, 123, 100, 95, 105, 115], {
    type: "line",
    height: "70",
    width: "100%",
    lineWidth: "2",
    lineColor: "#ffa534",
    fillColor: "rgba(255, 165, 52, .14)",
  });
</script>

src/templates/partials/sidebar.html
{% load static %}

{% url 'dashboard:index' as dashboard_index_url %}
{% url 'setting:edit_setting' as edit_setting_url %}
{% url 'teacher:add_teacher' as add_teacher_url %}
{% url 'teacher:list_teacher' as list_teacher_url %}
{% url 'student:add_student' as add_student_url %}
{% url 'student:list_student' as list_student_url %}
{% url 'student_cards:list_student_card' as list_student_card_url %}
{% url 'student_cards:add_student_card' as add_student_card_url %}
{% url 'absence:add_absence' as add_absence_url %}
{% url 'absence:list_absence' as list_absence_url %}
{% url 'adress:list_adress' as list_adress_url %}
{% url 'adress:add_adress' as add_adress_url %}
{% url 'role_user:add_role_user' as add_role_user_url %}
{% url 'role_user:list_role_user' as list_role_user_url %}
{% url 'user:list_user' as list_user_url %}
{% url 'user:add_user' as add_user_url %}
{% url 'report:index' as report_index_url %}
{% url 'school:edit_school' as edit_school_url %}

<div class="sidebar" data-background-color="dark">
    <div class="sidebar-logo">
        <!-- Logo Header -->
        <div class="logo-header" data-background-color="white">
            <a href="{% url 'dashboard:index' %}" class="logo">
                <img src="{% static 'assets/img/kaiadmin/logo_dark.png' %}" alt="navbar brand" class="navbar-brand" width="200" height="60"/>
            </a>
            <div class="nav-toggle">
                <button class="btn btn-toggle toggle-sidebar">
                    <i class="gg-menu-right"></i>
                </button>
                <button class="btn btn-toggle sidenav-toggler">
                    <i class="gg-menu-left"></i>
                </button>
            </div>
            <button class="topbar-toggler more">
                <i class="gg-more-vertical-alt"></i>
            </button>
        </div>
        <!-- End Logo Header -->
    </div>
    <div class="sidebar-wrapper scrollbar scrollbar-inner">
        <div class="sidebar-content">
            <ul class="nav nav-secondary">
                <li class="nav-item {% if request.path == dashboard_index_url %}active{% endif %}">
                    <a href="/" class="collapsed" aria-expanded="true">
                        <i class="fas fa-home"></i>
                        <p> Tableau de bord </p>
                    </a>
                </li>
                <li class="nav-section">
                <span class="sidebar-mini-icon">
                  <i class="fa fa-ellipsis-h"></i>
                </span>
                    <h4 class="text-section">Navigation</h4>
                </li>
                <li class="nav-item {% if request.path == add_teacher_url or request.path == list_teacher_url %} active {% endif %}">
                    <a data-bs-toggle="collapse" href="#base">
                        <i class="fas fa-layer-group"></i>
                        <p> Professeur </p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="base">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="{% url 'teacher:add_teacher' %}">
                                    <span class="sub-item">Nouveau Professeur</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'teacher:list_teacher' %}">
                                    <span class="sub-item">Liste des Professeurs</span>
                                </a>
                            </li>

                        </ul>
                    </div>
                </li>

                <li class="nav-item {% if request.path == add_student_url or request.path == list_student_url %}active{% endif %}">
                    <a data-bs-toggle="collapse" href="#sidebarLayouts">
                        <i class="fas fa-layer-group"></i>
                        <p> Elève </p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="sidebarLayouts">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="{% url 'student:add_student' %}">
                                    <span class="sub-item">Nouvel Elève</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'student:list_student' %}">
                                    <span class="sub-item">Liste des Elèves</span>
                                </a>
                            </li>

                        </ul>
                    </div>
                </li>

                <li class="nav-item {% if request.path == add_student_card or request.path == list_student_card_url %}active{% endif %}">
                    <a data-bs-toggle="collapse" href="#mserv">
                        <i class="fas fa-layer-group"></i>
                        <p> Carte Elève </p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="mserv">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="{% url 'student_cards:add_student_card' %}">
                                    <span class="sub-item">Nouvelle Carte</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'student_cards:list_student_card' %}">
                                    <span class="sub-item">Liste des Cartes</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item {% if request.path == add_absence_url or request.path == list_absence_url %}active{% endif %}">
                    <a data-bs-toggle="collapse" href="#sub">
                        <i class="fas fa-layer-group"></i>
                        <p> Absence </p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="sub">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="{% url 'absence:add_absence' %}">
                                    <span class="sub-item">Nouvelle Absence</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'absence:list_absence' %}">
                                    <span class="sub-item">Liste des Absences</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item {% if request.path == add_adress_url or request.path == list_adress_url %}active{% endif %}">
                    <a data-bs-toggle="collapse" href="#mape">
                        <i class="fas fa-layer-group"></i>
                        <p> Adresse </p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="mape">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="{% url 'adress:add_adress' %}">
                                    <span class="sub-item">Nouvelle Adresse</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'adress:list_adress' %}">
                                    <span class="sub-item">Liste des Adresses</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item {% if request.path == add_role_user_url or request.path == list_role_user_url %}active{% endif %}">
                    <a data-bs-toggle="collapse" href="#mapee">
                        <i class="fas fa-layer-group"></i>
                        <p> Rôle Utilisateur </p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="mapee">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="{% url 'role_user:add_role_user' %}">
                                    <span class="sub-item">Nouveau rôle</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'role_user:list_role_user' %}">
                                    <span class="sub-item">Liste des rôles</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item {% if request.path == add_user_url or request.path == list_user_url %}active{% endif %}">
                    <a data-bs-toggle="collapse" href="#mpee">
                        <i class="fas fa-layer-group"></i>
                        <p> Utilisateur </p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="mpee">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="{% url 'user:add_user' %}">
                                    <span class="sub-item">Nouvel Utilisateur</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'user:list_user' %}">
                                    <span class="sub-item">Liste des Utilisateurs</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
 
                <li class="nav-item {% if request.path == report_index_url %}active{% endif %}">
                    <a href="{% url 'report:index' %}" class="collapsed" aria-expanded="true">
                        <i class="fas fa-file"></i>
                        <span class="sub-item">Rapports</span>
                    </a>
                </li>

                <li class="nav-item {% if request.path == edit_school_url %}active{% endif %}">
                    <a href="{% url 'school:edit_school' %}" class="collapsed" aria-expanded="true">
                        <i class="icon-settings"></i>
                        <span class="sub-item">Paramètre de l'Ecole</span>
                    </a>
                </li>

                <li class="nav-item {% if request.path == edit_setting_url %}active{% endif %}">
                    <a href="{% url 'setting:edit_setting' %}" class="collapsed" aria-expanded="true">
                        <i class="icon-settings"></i>
                        <span class="sub-item">Paramètre d'application</span>
                    </a>
                </li>
                
            </ul>
        </div>
    </div>
</div>